/* config_linux.h.

   This file was generated by hand for use on Linux environments when
   building with GNU make and GCC/G++.  It will have to be kept
   up-to-date by hand.
*/

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if the C++ compiler uses namespaces.  */
#define HAVE_NAMESPACE 1

/* Define if the C++ iostream library supports ios::binary.  */
#define HAVE_IOS_BINARY 1

/* Define if fstream::open() accepts a third parameter for umask. */
/* #define HAVE_OPEN_MASK 1 */

/* Define if we're compiling with Cygwin. */
/* #undef HAVE_CYGWIN */

/* Define if we're compiling using Windows Microsoft Visual C++. */
#undef WIN32_VC

/* The platform oconfig is compiled for.  This primarily controls the
   initial setting of the $[PLATFORM] variable. */
#define PLATFORM "Linux"

/* Define if you have the `getopt' function.  */
#define HAVE_GETOPT 1

/* Define if you have the <alloca.h> header file.  */
#define HAVE_ALLOCA_H 1

/* Define if you have the <dirent.h> header file.  */
#define HAVE_DIRENT_H 1

/* Define if you have the <io.h> header file.  */
#undef HAVE_IO_H

/* Define if you have the <iostream> header file.  */
#define HAVE_IOSTREAM 1

/* Define if you have the <malloc.h> header file.  */
#define HAVE_MALLOC_H 1

/* Define if you have the <minmax.h> header file.  */
/* #undef HAVE_MINMAX_H */

/* Define if you have the <regex.h> header file.  */
#define HAVE_REGEX_H 1

/* Define if you have the <sstream> header file.  */
#define HAVE_SSTREAM 1

/* Define if you have the <string.h> header file.  */
#define HAVE_STRING_H 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <sys/types.h> header file.  */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <sys/utime.h> header file.  */
#undef HAVE_SYS_UTIME_H

/* Define if you have the <sys/wait.h> header file.  */
#define HAVE_SYS_WAIT_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the <utime.h> header file.  */
#define HAVE_UTIME_H 1

/* Name of package */
#define PACKAGE "oconfig"

// platform POSIX helpers
#define OCONFIG_TEMPNAM tempnam
#define OCONFIG_UNLINK unlink
#define OCONFIG_CHDIR chdir

/****************  UPDATE VERSION NUMBER HERE  ****************
 **         Also be sure to change the version number        **
 **             at the beginning of configure.in.            **
 ****************                              ****************/
#define VERSION "2.5"
/****************  UPDATE VERSION NUMBER HERE  ****************/
